/**:
  ros__parameters:
    network_list_timeout: 5
    nethogs_timeout: 5
    reassemble_timeout: 5
    devices: ["*"]
    monitor_program: "greengrass"
    crc_error_check_duration: 1
    crc_error_count_threshold: 1
    reassembles_failed_check_duration: 1
    reassembles_failed_check_count: 1
